version: '3.8'

services:
  postgres:
    image: postgres:latest
    ports:
      - "8000:5432"
    environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin123
        POSTGRES_DB: test
        